# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* account_online_sync_ar
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 13.0+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-07-27 19:30+0000\n"
"PO-Revision-Date: 2021-07-27 19:30+0000\n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"100: Register - The API registers a new process (through a REST request)"
msgstr ""
"100: Registro: la API registra un nuevo proceso (a través de una solicitud "
"REST)"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"101: Starting - The process information was obtained to start operating"
msgstr ""
"101: Iniciando - Se obtuvo la información del proceso para comenzar a operar"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "102: Running - The process is running (login successful)"
msgstr ""
"102: En ejecución: el proceso se está ejecutando (inicio de sesión exitoso)"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "103: TokenReceived - The process received the token"
msgstr "103: Token Recibido: el proceso recibió el token"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"200: Finish - The connection has been successful. Data has been extracted"
msgstr ""
"200: Finalizado: la conexión se ha realizado correctamente. Se han extraído "
"los datos"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"201: Pending - The connection has been successful. We have partially "
"extracted information but data will still be extracted in background "
"processes."
msgstr ""
"201: Pendiente: la conexión se ha realizado correctamente. Hemos extraído "
"parcialmente la información, pero los datos se seguirán extrayendo en "
"procesos de fondo."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"202: NoTransactions - The connection has been successful. However, no "
"transactions were found."
msgstr ""
"202: Sin Transacciones: la conexión se ha realizado correctamente. Sin "
"embargo, no se encontraron transacciones."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"203: PartialTransactions - The connection has been successful. However, more"
" than one account does not have transactions."
msgstr ""
"203: Transacciones Parciales: la conexión se ha realizado correctamente. Sin"
" embargo, más de una cuenta no tiene transacciones."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"204: Incomplete - The connection has been successful. However, the data "
"downloaded is incompleted."
msgstr ""
"204: Incompleto: la conexión se ha realizado correctamente. Sin embargo, los"
" datos descargados están incompletos."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"206: NoAccounts - The connection has been successful. However, there were no"
" accounts linked to the given credentials."
msgstr ""
"206: No hay Cuentas: la conexión se ha realizado correctamente. Sin embargo,"
" no había cuentas vinculadas a las credenciales proporcionadas."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "400: Bad Request."
msgstr "400: Petición Incorrecta."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"401: Unauthorized - The value of one of the given Authentication Fields was "
"not accepted by the institution. Please verify the information and try "
"again."
msgstr ""
"401: No autorizado: la institución no aceptó el valor de uno de los campos "
"de autenticación proporcionados. Verifique la información y vuelva a "
"intentarlo."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "402: Payment Required"
msgstr "402: Pago requerido"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"403: Forbidden or Invalidtoken - The given token value introduced was not "
"accepted by the institution or the expiration time was reached."
msgstr ""
"403: Prohibido or Token Invalido: la institución no aceptó el valor del "
"token introducido o se alcanzó el tiempo de vencimiento."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "404: Not Found."
msgstr "404: No encontrado."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"405: Locked - The institution has blocked the given credential, please "
"contact your institution and make sure your connection to the site is "
"working properly before trying again."
msgstr ""
"405: Bloqueado: la institución ha bloqueado la credencial proporcionada, "
"comuníquese con su institución y asegúrese de que su conexión con el sitio "
"funcione correctamente antes de volver a intentarlo."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"406: Conflict - The institution does not allow to have more than one user "
"logged in. If you have logged in to your institution using another device, "
"please make sure to log out before trying again."
msgstr ""
"406: Conflicto: la institución no permite que haya más de un usuario conectado. Si ha iniciado sesión en su institución con otro dispositivo, asegúrese de cerrar la sesión antes de volver a intentarlo.\n"
"\n"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"408: UserAction - The institution requires attention from the user. We "
"advise you to log in to the institution to confirm everything is working "
"properly. Upon confirmation, try again."
msgstr ""
"408: Acción del Usuario: La institución requiere la atención del usuario. Le"
" recomendamos que inicie sesión en la institución para confirmar que todo "
"funciona correctamente. Tras la confirmación, inténtelo de nuevo."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"409: WrongSite - The given credentials seem to be valid but they belong to a"
" different site from the same organization."
msgstr ""
"409: Sitio Equivocado: las credenciales proporcionadas parecen ser válidas "
"pero pertenecen a un sitio diferente de la misma organización."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "410: Waiting - Waiting for MFA Value"
msgstr "410: Esperando - Esperando valor de MFA"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"411: TwofaTimeout - The time to introduce the MFA value has been exceeded."
msgstr "411: TwofaTimeout: se superó el tiempo para introducir el valor MFA."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "413: LoginError - There is a error in Login Process, please try again."
msgstr ""
"413: LoginError: hay un error en el proceso de inicio de sesión,  inténtelo "
"de nuevo."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "429: Too Many Requests."
msgstr "429: Demasiadas solicitudes."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"500: Error - An internal error has been ocurred while connecting to the "
"institution"
msgstr ""
"500: Error - Se produjo un error interno al conectarse a la institución"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"501: Unavailable - The institución has informed to us that there was a "
"problem in the connection"
msgstr ""
"501: No disponible - La institución nos ha informado que hubo un problema en "
"la conexión"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "503: Service Unavailable."
msgstr "503: Servicio no Disponible.\n"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"504: ConnectionTimeout - An internal error has been ocurred while connecting"
" to the institution."
msgstr ""
"504: ConnectionTimeout - Se ha producido un error interno al conectarse a la"
" institución."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "509: UndergoingMaintenance - The institution is under maintenance."
msgstr "509: Sometido a mantenimiento: la institución está en mantenimiento."

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.update_credential
msgid "Actualizar Credencial del Banco"
msgstr ""

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.online_provider_account_form_view
msgid "Add/Configure accounts"
msgstr "Agregar/Configurar cuentas"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "An error has occurred (code %s)"
msgstr "Un error ha ocurrido (código %s)"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "Bad Request."
msgstr ""

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.online_provider_account_form_view
msgid "Check Status"
msgstr "Verificar Status"

#. module: account_online_sync_ar
#: model:ir.model,name:account_online_sync_ar.model_res_company
msgid "Companies"
msgstr "Compañías"

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.paybook_login
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.update_credential
msgid "Company ID"
msgstr "ID Compañía"

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.paybook_login
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.update_credential
msgid "Credential ID"
msgstr ""

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.online_provider_account_form_view
msgid "Delete Online Credentials"
msgstr "Eliminar Credenciales en línea"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/res_company.py:0
#, python-format
msgid ""
"Falta configuración de credenciales de ADHOC para consulta del user token"
msgstr ""

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/res_company.py:0
#, python-format
msgid "Falta configuración de credenciales de ADHOC para creacion de new user"
msgstr ""

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.online_provider_account_form_view
msgid "Force Sync"
msgstr "Forzar Sincronización"

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.update_credential
msgid "ID Site"
msgstr "ID del Sitio"

#. module: account_online_sync_ar
#: model:ir.model,name:account_online_sync_ar.model_account_online_journal
msgid "Interface for Online Account Journal"
msgstr "Interfaz para el diario de cuenta en línea"

#. module: account_online_sync_ar
#: model:ir.model,name:account_online_sync_ar.model_account_journal
msgid "Journal"
msgstr "Diario"

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.paybook_login
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.update_credential
msgid "Journal ID"
msgstr "ID del Diario"

#. module: account_online_sync_ar
#: model:ir.model.fields,field_description:account_online_sync_ar.field_account_bank_statement_import_journal_creation__paybook_last_transaction
#: model:ir.model.fields,field_description:account_online_sync_ar.field_account_journal__paybook_last_transaction
msgid "Last synced transaction"
msgstr "Ultima transacción sincronizada"

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.account_journal_dashboard_inherit_online_sync
msgid "Last:"
msgstr "Última:"

#. module: account_online_sync_ar
#: model:ir.model.fields,field_description:account_online_sync_ar.field_account_bank_statement_import_journal_creation__paybook_next_available
#: model:ir.model.fields,field_description:account_online_sync_ar.field_account_journal__paybook_next_available
#: model:ir.model.fields,field_description:account_online_sync_ar.field_account_online_provider__paybook_next_refresh
msgid "Next transactions will be available at"
msgstr "Próximas transacciones estarán disponibles el"

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.account_journal_dashboard_inherit_online_sync
msgid "Next:"
msgstr "Próxima:"

#. module: account_online_sync_ar
#: model:ir.model.fields,field_description:account_online_sync_ar.field_account_online_provider__next_refresh
msgid "Odoo cron next run"
msgstr "Próxima corrida de acción planificada en Odoo"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#: model:ir.model.fields.selection,name:account_online_sync_ar.selection__account_online_provider__provider_type__paybook
#, python-format
msgid "Paybook"
msgstr ""

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.paybook_login
msgid "Paybook Odoo"
msgstr "Odoo Paybook"

#. module: account_online_sync_ar
#: model:ir.model.fields,field_description:account_online_sync_ar.field_res_company__paybook_user_id
msgid "Paybook User ID"
msgstr "ID Usuario Paybook"

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.paybook_login
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.update_credential
msgid "Paybook User Token"
msgstr ""

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid ""
"Paybook fetch: Please comunicate with your Odoo Provider. This is what we "
"got %s"
msgstr "Paybook fetch: Por favor comuniquese con tu Proveedor de Odoo. Esto es lo que obtenemos "

#. module: account_online_sync_ar
#: model:ir.actions.server,name:account_online_sync_ar.ir_cron_paybook_update_transactions_ir_actions_server
#: model:ir.cron,cron_name:account_online_sync_ar.ir_cron_paybook_update_transactions
#: model:ir.cron,name:account_online_sync_ar.ir_cron_paybook_update_transactions
msgid "Paybook: Update transactions"
msgstr "Paybook: Actualizar transacciones"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "Payment Required"
msgstr ""

#. module: account_online_sync_ar
#: model:ir.model.fields,field_description:account_online_sync_ar.field_account_bank_statement_import_journal_creation__account_online_provider_type
#: model:ir.model.fields,field_description:account_online_sync_ar.field_account_journal__account_online_provider_type
#: model:ir.model.fields,field_description:account_online_sync_ar.field_account_online_provider__provider_type
msgid "Provider Type"
msgstr "Tipo de Proveedor"

#. module: account_online_sync_ar
#: model:ir.model,name:account_online_sync_ar.model_account_online_provider
msgid "Provider for online account synchronization"
msgstr "Proveedor de sincronización de cuenta en línea"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "Server not reachable, please try again later"
msgstr ""
"No se puede acceder al servidor, por favor intente otra vez más tarde. "

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "Service Unavailable."
msgstr "Serivio No disponibl"

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.update_credential
msgid "State"
msgstr "Estado"

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.paybook_login
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.update_credential
msgid "Test it"
msgstr "Pruébalo"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "The next transactions sync will be available in %s hours"
msgstr "Las próximas transacciones estarán disponibles en %s horas"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "There is not account credential to be deleted"
msgstr "No hay cuenta/credencial para ser borrada"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_journal.py:0
#, python-format
msgid ""
"These transactions have been deleted or disable by the bank provider, please"
" review them and if needed unreconcile them, delete them and try to "
"reconcile with the proper bank statement line. You can check this in action "
"menu \"Find possible duplicates\""
msgstr ""
"Estas transacciones han sido eliminadas o deshabilitadas por el proveedor del banco, por favor"
" reviselas y si es necesario desconcilielas, eliminelas e intente conciliarlas "
"nuevamente con la linea de extracto bancario mas apropiada. Puede revisar esto en el menú "
"acción  \"Encontrar posibles duplicados\""

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.online_provider_account_form_view
msgid ""
"This action can not be undone. Are you sure? This can affect any other "
"database using the same credential"
msgstr ""
"Esta acción no se puede deshacer. ¿Está seguro? Esto puede afectar a "
"cualquier otra base de datos que utilice la misma credencial."

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "Timeout: the server did not reply within 60s"
msgstr "Se agotó el tiempo: El servidor no ha respondido en 60s"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "Unknown exception %s"
msgstr "Excepción Desconocida %s"

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.online_provider_account_form_view
msgid "Update Password"
msgstr "Actualizar Contraseña"

#. module: account_online_sync_ar
#: model_terms:ir.ui.view,arch_db:account_online_sync_ar.online_provider_account_form_view
msgid "Update/Fix"
msgstr "Actualizar/Corregir"

#. module: account_online_sync_ar
#: code:addons/account_online_sync_ar/models/account_online_provider.py:0
#, python-format
msgid "We don't find any new account to add / configure"
msgstr "No encontramos ningúna cuenta que agregar / configurar "
